# Generated by Django 5.0.6 on 2024-05-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
