# Generated by Django 5.0.6 on 2024-05-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hints/'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
