# Generated by Django 5.0.6 on 2024-05-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigments', '0002_hint_image_alter_hint_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
